gcp_credentials: ENCRYPTED[d84e50350f4a53180dc8bda3a637b0da5a7f5526b2f648b0e8e7a52379de1328b203b98296e439e8eb83e00ec6675ca1]

standard_build: &standard_build
  configure_script:
    - su build -c ./bootstrap
    - su build -c ./configure
  build_client_script:
    - su build -c 'make build-backup-client'
  build_server_script:
    - su build -c 'make build-backup-server'
  test_script:
    - su build -c 'make debug_tests'
    
debian_test_task:
  gce_instance:
    image_project: debian-cloud
    image_name: debian-9-stretch-v20190618
    zone: europe-west2-c
    type: n1-standard-2  # 2 vCPU, 7.5GB mem
    disk: 10
    use_ssd: true
    #preemptible: $CIRRUS_BRANCH != "master"
    
  pre_script:
    - echo "User: $USER"
    - id
    - apt-get update
    - apt-get install -y git autoconf automake gcc g++ zlib1g-dev libssl-dev libdb-dev libreadline-dev libeditline-dev make xsltproc libwww-perl libboost-dev
    - useradd -m build
    - chown -R build: .
  <<: *standard_build

freebsd_test_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  pre_script:
    - echo "User: $USER"
    - id
    - pkg install -y git autoconf automake libxslt p5-libwww boost-libs
    - pw useradd build -m -w none
    - chown -R build: .
  <<: *standard_build
